### ISSUE TITLE
Calling `#from_hash`: NoMethodError: undefined method `has_key?' for nil:NilClass

### ISSUE THREAD

**Issue by moxley** [apotonick/representable#115]
When calling `#from_hash` or `#from_json` with parameters that contain `nil` for a nested property, it raises the following error:

```
NoMethodError: undefined method `has_key?' for nil:NilClass
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/hash/binding.rb:13:in `read'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/binding.rb:64:in `read_fragment'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/binding.rb:45:in `block in uncompile_fragment'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/binding.rb:99:in `evaluate_option'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/binding.rb:44:in `uncompile_fragment'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/mapper.rb:68:in `uncompile_fragment'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/mapper.rb:35:in `deserialize_property'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/mapper.rb:15:in `block in deserialize'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/mapper.rb:14:in `each'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/mapper.rb:14:in `deserialize'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable.rb:34:in `update_properties_from'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/hash.rb:31:in `from_hash'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/deserializer.rb:31:in `block in deserialize'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/binding.rb:99:in `evaluate_option'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/deserializer.rb:30:in `deserialize'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/deserializer.rb:23:in `call'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/populator.rb:34:in `deserialize'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/populator.rb:20:in `call'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/binding.rb:66:in `read_fragment'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/binding.rb:45:in `block in uncompile_fragment'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/binding.rb:99:in `evaluate_option'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/binding.rb:44:in `uncompile_fragment'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/mapper.rb:68:in `uncompile_fragment'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/mapper.rb:35:in `deserialize_property'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/mapper.rb:15:in `block in deserialize'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/mapper.rb:14:in `each'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/mapper.rb:14:in `deserialize'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable.rb:34:in `update_properties_from'
    ruby-2.1.2/gems/representable-2.1.0/lib/representable/hash.rb:31:in `from_hash'
    null_child_test.rb:27:in `block in <class:NullChildTest>'
```

Here's a test that reproduces it:

```ruby
require 'minitest/autorun'
require 'representable/json'

class NullChildTest < MiniTest::Spec
  class ParentClass
    attr_accessor :child
  end

  class ChildClass
    attr_accessor :id
  end

  module ChildClassRepresenter
    include Representable::JSON
    property :id
  end

  module ParentClassRepresenter
    include Representable::JSON
    property :child, class: ChildClass, extend: ChildClassRepresenter
  end

  it "allows child to be nil" do
    parent = ParentClass.new.extend(ParentClassRepresenter)

    # Raises error: undefined method `has_key?` for nil:NilClass
    parent.from_hash 'child' => nil
  end
end
```

Gemfile:

```ruby
gem "representable", git: 'git@github.com:apotonick/representable.git', ref: 'master'
gem "minitest"
```

Is there any way to allow a `nil` value for the child? I don't have a workaround other than manually looking for `nil` in the input hash for the child property and deleting it from the Hash.

**Comment by mhuggins** [comment]
I'm running into this issue as well.  Using `skip_parse` is a legit workaround, but it's very painful and time consuming to have to include `skip_parse` on every custom parsed property (i.e.: one that utilizes the `extend` option).

```ruby
property :bio, extend: BioRepresenter, class: Bio, render_nil: false,
    skip_parse: ->(fragment, options) { fragment.nil? }
collection :songs, extend: SongRepresenter, class: Song, render_empty: false,
    skip_parse: ->(fragment, options) { fragment.nil? }
collection :albums, extend: AlbumRepresenter, class: Album, render_empty: false,
    skip_parse: ->(fragment, options) { fragment.nil? }
# etc...
```

I'll try to take a look at the open PR to see if I can offer any help, but I just wanted to share my frustration with it as well so OP knows he's not alone. :)

**Comment by mhuggins** [comment]
I suppose using ActiveSupport `with_options` could help here FWIW.

**Comment by apotonick** [comment]
@mhuggins You're not really using that `:skip_parse` hack everywhere? Jeez - if this is such a problem then hit me up via email and make me fix it. Will look into it now!

**Comment by apotonick** [comment]
@moxley I merged your test and found out a weird inconsistency. You do

```ruby
 it "sets represented property to nil when incoming value is nil" do
      portland = Hometown.new
      portland.name = "Portland"
      @band.hometown = portland
      @band.from_hash 'hometown' => nil
      assert_equal nil, @band.hometown.name
```

So, you say `from_hash {hometown: nil}` but then you test `band.hometown.name`, which works with your fix. However, `hometown` should be `nil` - at least, that's how I would interpret `{hometown: nil}`. Any ideas?

**Comment by apotonick** [comment]
In other words:

```ruby
from_hash nested_property: nil
```

should basically do `represented.nested_property = nil` in order to allow people do delete associated objects, right?

**Comment by mhuggins** [comment]
Without looking at the code, my guess is that the change is creating a "blank" object of whatever the `class` is.  e.g.: `property :foo, extend: FooRepresenter, class: Foo` ends up creating a `Foo` instance without any attributes set, maybe?

**Comment by apotonick** [comment]
Yepp, that's what happens, but that's wrong! What you describe should happen for a document as `{nested_property: {}}`.

**Comment by mhuggins** [comment]
Yep, that makes sense to me.  It seems like the more appropriate change might be to modify this line in `representable/hash/binding.rb`, from this:

```ruby
return FragmentNotFound unless hash.has_key?(as)
```

to this:

```ruby
return FragmentNotFound if hash.nil? || !hash.has_key?(as)
```

This is just from eyeballing the representable code though, totally untested. :)

**Comment by mhuggins** [comment]
The reason I suspect that's where the change belongs is because the error message I get is:

```
NoMethodError: undefined method `has_key?' for nil:NilClass
```

with a stack trace that leads to:

```
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/hash/binding.rb:14 :in `read`
```

**Comment by mhuggins** [comment]
Ahh, I'm probably wrong actually.  I think the code reaches that point when it's already trying to parse the nested property.  So the change is somewhere earlier in the full stack trace:

```
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/hash/binding.rb:14 :in `read`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:83 :in `read_fragment`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:64 :in `block in uncompile_fragment`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:120 :in `evaluate_option`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:63 :in `uncompile_fragment`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:77 :in `uncompile_fragment`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:38 :in `deserialize_property`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:18 :in `block in deserialize`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:17 :in `each`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:17 :in `deserialize`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable.rb:41 :in `update_properties_from`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/hash.rb:31 :in `from_hash`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:36 :in `demarshal`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:31 :in `block in deserialize`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:120 :in `evaluate_option`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:30 :in `deserialize`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:23 :in `call`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/populator.rb:35 :in `deserialize`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/populator.rb:21 :in `call`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:85 :in `read_fragment`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:64 :in `block in uncompile_fragment`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:120 :in `evaluate_option`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:63 :in `uncompile_fragment`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:77 :in `uncompile_fragment`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:38 :in `deserialize_property`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:18 :in `block in deserialize`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:17 :in `each`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:17 :in `deserialize`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable.rb:41 :in `update_properties_from`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/hash.rb:31 :in `from_hash`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:36 :in `demarshal`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:31 :in `block in deserialize`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:120 :in `evaluate_option`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:30 :in `deserialize`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:23 :in `call`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:97 :in `deserialize!`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:89 :in `block in call`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:85 :in `each`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:85 :in `each_with_index`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/deserializer.rb:85 :in `call`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/populator.rb:49 :in `deserialize`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/populator.rb:21 :in `call`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:85 :in `read_fragment`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:64 :in `block in uncompile_fragment`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:120 :in `evaluate_option`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/binding.rb:63 :in `uncompile_fragment`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:77 :in `uncompile_fragment`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:38 :in `deserialize_property`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:18 :in `block in deserialize`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:17 :in `each`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/mapper.rb:17 :in `deserialize`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable.rb:41 :in `update_properties_from`
[GEM_ROOT]/gems/representable-2.2.3/lib/representable/hash.rb:31 :in `from_hash`
```

**Comment by mhuggins** [comment]
I think the logic for [skip_property?](https://github.com/apotonick/representable/blob/082de142e410275469daa3b39ae2aa30dd52aae5/lib/representable/mapper.rb#L46) needs to be updated now that I'm digging a little more.

**Comment by mhuggins** [comment]
:+1: :heart: Thanks a ton for your help on this @apotonick!!  You rock!
