### ISSUE TITLE
2.4 is missing Representable::Feature?

### ISSUE THREAD

**Issue by PikachuEXE** [apotonick/representable#169]
Backtrace: 
```
/Users/PikachuEXE/.rvm/gems/ruby-2.2.3/gems/disposable-0.1.14/lib/disposable/twin.rb:40:in `<class:Twin>': uninitialized constant Representable::Feature (NameError)
	from /Users/PikachuEXE/.rvm/gems/ruby-2.2.3/gems/disposable-0.1.14/lib/disposable/twin.rb:23:in `<module:Disposable>'
	from /Users/PikachuEXE/.rvm/gems/ruby-2.2.3/gems/disposable-0.1.14/lib/disposable/twin.rb:22:in `<top (required)>'
	from /Users/PikachuEXE/.rvm/gems/ruby-2.2.3/gems/reform-2.0.5/lib/reform/contract.rb:2:in `<top (required)>'
	from /Users/PikachuEXE/.rvm/gems/ruby-2.2.3/gems/reform-2.0.5/lib/reform.rb:7:in `<top (required)>'
	from /Users/PikachuEXE/Projects/somewhere.rb:3:in `<top (required)>'
```

**Comment by apotonick** [comment]
You need to upgrade to disposable 0.2.0.

**Comment by PikachuEXE** [comment]
And here is the reason why I cannot upgrade: https://github.com/apotonick/reform/blob/v2.0.5/reform.gemspec#L20 :grin:

**Comment by apotonick** [comment]
Use Reform master, I will push a `pre` this weekend.
