### ISSUE TITLE
Representable::YAML breaks if Representable::Hash is also included

### ISSUE THREAD

**Issue by michaelmior** [apotonick/representable#180]
It seems it isn't possible to have both `to_hash` and `to_yaml` in a decorator.

```ruby
require 'yaml'

require 'representable'
require 'representable/yaml'

class IndexRepresenter < Representable::Decorator
  include Representable::YAML
  # The error goes away when I comment out the line below
  include Representable::Hash

  property :key
end

require 'ostruct'
index = OpenStruct.new
index.key = 'key'
p IndexRepresenter.represent(index).to_yaml
```

I get the error message below.

```text
/home/mmior/apps/representable/lib/representable/hash/binding.rb:16:in `write': undefined method `[]=' for #<Psych::Nodes::Mapping:0x00000002fbe080> (NoMethodError)
        from /home/mmior/apps/representable/lib/representable/serializer.rb:47:in `block in <module:Representable>'
        from /home/mmior/apps/representable/lib/representable/pipeline.rb:18:in `call'
        from /home/mmior/apps/representable/lib/representable/pipeline.rb:18:in `evaluate'
        from /home/mmior/apps/representable/lib/representable/pipeline.rb:10:in `block in call'
        from /home/mmior/apps/representable/lib/representable/pipeline.rb:9:in `each'
        from /home/mmior/apps/representable/lib/representable/pipeline.rb:9:in `inject'
        from /home/mmior/apps/representable/lib/representable/pipeline.rb:9:in `call'
        from /home/mmior/apps/representable/lib/representable/binding.rb:36:in `compile_fragment'
        from /home/mmior/apps/representable/lib/representable/deprecations.rb:112:in `compile_fragment'
        from /home/mmior/apps/representable/lib/representable.rb:52:in `block in call'
        from /home/mmior/apps/representable/lib/representable.rb:50:in `each'
        from /home/mmior/apps/representable/lib/representable.rb:50:in `call'
        from /home/mmior/apps/representable/lib/representable.rb:69:in `representable_map!'
        from /home/mmior/apps/representable/lib/representable.rb:44:in `create_representation_with'
        from /home/mmior/apps/representable/lib/representable/yaml.rb:30:in `block in to_ast'
        from /home/mmior/apps/representable/lib/representable/yaml.rb:29:in `tap'
        from /home/mmior/apps/representable/lib/representable/yaml.rb:29:in `to_ast'
        from /home/mmior/apps/representable/lib/representable/yaml.rb:38:in `to_yaml'
        from test.rb:17:in `<main>'
```

Swapping the order makes `to_yaml` work but then `to_hash` is broken with the following error:

```text
/home/mmior/apps/representable/lib/representable/hash/binding.rb:16:in `write': undefined method `[]=' for #<Psych::Nodes::Mapping:0x00000002fbe080> (NoMethodError)
        from /home/mmior/apps/representable/lib/representable/serializer.rb:47:in `block in <module:Representable>'
        from /home/mmior/apps/representable/lib/representable/pipeline.rb:18:in `call'
        from /home/mmior/apps/representable/lib/representable/pipeline.rb:18:in `evaluate'
        from /home/mmior/apps/representable/lib/representable/pipeline.rb:10:in `block in call'
        from /home/mmior/apps/representable/lib/representable/pipeline.rb:9:in `each'
        from /home/mmior/apps/representable/lib/representable/pipeline.rb:9:in `inject'
        from /home/mmior/apps/representable/lib/representable/pipeline.rb:9:in `call'
        from /home/mmior/apps/representable/lib/representable/binding.rb:36:in `compile_fragment'
        from /home/mmior/apps/representable/lib/representable/deprecations.rb:112:in `compile_fragment'
        from /home/mmior/apps/representable/lib/representable.rb:52:in `block in call'
        from /home/mmior/apps/representable/lib/representable.rb:50:in `each'
        from /home/mmior/apps/representable/lib/representable.rb:50:in `call'
        from /home/mmior/apps/representable/lib/representable.rb:69:in `representable_map!'
        from /home/mmior/apps/representable/lib/representable.rb:44:in `create_representation_with'
        from /home/mmior/apps/representable/lib/representable/yaml.rb:30:in `block in to_ast'
        from /home/mmior/apps/representable/lib/representable/yaml.rb:29:in `tap'
        from /home/mmior/apps/representable/lib/representable/yaml.rb:29:in `to_ast'
        from /home/mmior/apps/representable/lib/representable/yaml.rb:38:in `to_yaml'
        from test.rb:17:in `<main>'
```

Any help figuring out how to make this work would be appreciated :)

**Comment by michaelmior** [comment]
After some digging, this appears to be tied to `Representable::Cached`. If I remove that include from `Representable::Decorator`, things work as expected.

**Comment by michaelmior** [comment]
Definitely a caching issue. I was able to solve this in my actual code by including the following module which restores the original behaviour of `representable_map`.

```ruby
module Uncached
  def representable_map(options, format)
    Representable::Binding::Map.new(representable_bindings_for(format, options))
  end
end
```

Any thoughts on how caching could continue to work while supporting this use case?

**Comment by apotonick** [comment]
The decorator is designed to support only 1 representer engine, so we can set up bindings at compile-time, speeding up Representable 2.4 by factor x. The fact that this worked prior to 2.4 was "an accident" and was never documented anywhere...

It's definitely possible to allow multiple engines, with caching, but, honestly, I don't need it and I have a hundred other things on my plate. If you come up with a clean solution that's equally fast as it is now, I'm happy to merge it. Sorry if that's a bummer for you... :beer:

**Comment by michaelmior** [comment]
No worries. I understand :) I have a solution that works at least. I see there are already some benchmarking scripts in the repo so I'll try to give it a stab sometime. I'll close this out for now.

**Comment by apotonick** [comment]
I actually played with that a while ago but it was always slower because I saved the different bindings in a hash, and the lookup wasted shitloads of time (when you do that 5000x per "request" it matters), but maybe we can find a better way?
